name: Trigger auto deployment for container-app-qqkcziyg2vxbo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-qqkcziyg2vxbo-AutoDeployTrigger-d16a0358-6dde-4b84-8340-60a6297441cf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQQKCZIYG2VXBO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQQKCZIYG2VXBO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQQKCZIYG2VXBO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryqqkcziyg2vxbo.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPQQKCZIYG2VXBO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQQKCZIYG2VXBO_REGISTRY_PASSWORD }}
          containerAppName: container-app-qqkcziyg2vxbo
          resourceGroup: expresshello8abf94ff
          imageToBuild: containerregistryqqkcziyg2vxbo.azurecr.io/container-app-qqkcziyg2vxbo:${{ github.sha }}
          


